version: '2'
services:
  postgres-db:
    image: postgres:10.5-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      mynetwork:
    volumes:
      - ./src/db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
networks:
  mynetwork: