service: prueba-tecnica

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: 'aws'
  runtime: 'nodejs14.x'
  region: 'eu-west-3'
  stage: 'local'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

functions:

  putItem:
    handler: dist/handlers/put-item.putItemHandler
    events:
      - http:
          method: 'post'
          path: '/'
          request:
            schemas:
              application/json: schema

  putCompany:
    handler: dist/handlers/put-company.putCompanyHandler
    events:
      - http:
          method: post
          path: /put-company

  putUser:
    handler: dist/handlers/put-user.putUserHandler
    events:
      - http:
          method: post
          path: /put-user

  putOffering:
    handler: dist/handlers/put-offering.putOfferingHandler
    events:
      - http:
          method: post
          path: /put-offering

  invest:
    handler: dist/handlers/invest.investHandler
    events:
      - http:
          method: post
          path: /invest

  getAllCompanies:
    handler: dist/handlers/get-all-companies.getAllCompaniesHandler
    events:
      - http:
          method: get
          path: /get-all-companies

  getAllInvestorsByCompany:
    handler: dist/handlers/get-all-investors-by-company.getAllInvestorsByCompanyHandler
    events:
      - http:
          method: get
          path: /get-all-investors-by-company/{id}
package:
  individually: true

custom:
  region: ${self:provider.region}
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'aws-sdk'
    target: 'node14'
    define:
      require.resolve: undefined
    platform: 'node'
    concurrency: 10,
 