name: Lambda pipeline

on: [push]

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Installing
        run: npm install
      - name: Testing
        run: npm run test
